<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<h1>Bjarnes Bank</h1>

<form method="POST" action="AccountController.php">
  First Name:<br>
  <input type="text" name="firstname" value=""><br>
  Last Name:<br>
  <input type="text" name="lastname" value=""><br>
  User Name:<br>
  <input type="text" name="username" value=""><br>
  Email:<br>
  <input type="text" name="email" value=""><br>
  Phone Number:<br>
  <input type="text" name="phonenumber" value=""><br>
  Street Name:<br>
  <input type="text" name="streetname" value=""><br>
  Street Number:<br>
  <input type="text" name="streetnumber" value=""><br>
  Suburb:<br>
  <input type="text" name="suburb" value=""><br>
  Country:<br>
  <input type="text" name="country" value=""><br>
  Post Code:<br>
  <input type="text" name="postcode" value=""><br>
  Password:<br>
  <input type="text" name="password" value=""><br>
  Verify Password:<br>
  <input type="text" name="passwordverified" value=""><br>
  <input type="submit" value="Create Account">
</form>

<a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>