<?php include "header.phtml" ?>


<div id="wrapper">
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<img src="/images/BjarnesLogo.png" width="90" height="170" alt="Logo" />
				<h1><a href="#">Bjarnes Bank</a></h1>
			</div>
			<div id="menu">
				<ul>
					<li ><a href=<?= $linkTo('loginPage'); ?>>Log in</a></li>
					<li class="current_page_item"><a href="#">Join</a></li>
				</ul>
			</div>
		</div>
	</div>

	<!------header wrapper ends ----------------->



	<div id="usercreate">
		<h3><b> Create an Account</b></h3>
		<br>
		<form method="POST" action="<?= $linkTo('bankAccountCreate'); ?>">
			
		<div id="personinfo">
			<p> Account Name  <input type="text" name="AccountName" pattern="[A-Za-z]{1,}" title="Alphanumeric characters only with no spaces." size="25"> </p>
			<p> Account Type  <select name="AccountType">
                    <option value="Savings">Savings</option>
                    <option value="Cheque">Cheque</option>
                    <option value="FastSaver">FastSaver</option>
                </select> </p>
			<br>
		</div>
			<input class="login" type="submit" value="Create"> </p>
		</form>

	</div>
	<!------User Create ends ----------------->

</div>


<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>