

<?php

session_start();


include "header.phtml"

?>


<div id="wrapper">
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<img src="../../images/BjarnesLogo.png" width="90" height="170" alt="Logo" />
				<h1><a href="<?= $linkTo('homePage'); ?>">Bjarnes Bank</a></h1>
			</div>
			<div id="menu">
				<ul>
                    <li><a href="<?= $linkTo('homePage'); ?>">Homepage</a></li>
                    <li><a href="<?= $linkTo('bankAccount'); ?>">Create Account</a></li>
                    <li><a href="<?= $linkTo('logOut'); ?>">Log out</a></li>
				</ul>
			</div>
		</div>
	</div>

	<!------header wrapper ends ----------------->
    <div id="page">
        <div id="content">
            <div class="entry">
                <form method="POST" action="<?= $linkTo('bankAccountCloseAction'); ?>">
                    <?php if(!$_SESSION['validTransaction']){
                        print("<p>Invalid Payment </p><br>");
                    }
                    ?>

                    <p> From:  <select name="accountClose">

                            <?php

                            for($i = 0; $i < count($accounts);$i++){

                            ?>

                            <option value="<?= $accounts[$i][1]?>"><?= $accounts[$i][1]."   \t $".money_format('%.2n', $accounts[$i][2])?></option>

                            <?php
                            }
                            ?>

                        </select> </p>
                    <br>





                    <input class="transfer" type="submit" value="Delete" > </p>
                </form>

            </div>
            <!------Login ends ----------------->

        </div>
        <div id="sidebar">
            <ul>
                <li>
                    <h2>Categories</h2>
                    <ul>
                        <li><a href="<?= $linkTo('transferPage'); ?>">Make Transfer</a></li>
                        <li><a href="<?= $linkTo('paymentPage'); ?>">Make Payment</a></li>
                        <li><a href="<?= $linkTo('closeAccountPage'); ?>">Close Account</a></li>
                        <li><a href="<?= $linkTo('typeAccountPage'); ?>">Types of accounts</a></li>
                        <li><a href="<?= $linkTo('aboutus'); ?>">About us</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- end #sidebar -->
    </div>
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>