<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bjarnes Bank Ltd</title>
<meta name="keywords" content="Bjarnes Bank" />
<meta name="description" content="Safe, Secure, Fast DOller Handlers, so give is ya money, Yeet" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />
<link href="..\..\static\styles\style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<!---------- Header ends --------------->