

<?php

session_start();


include "header.phtml"

?>


<div id="wrapper">
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<img src="images/BjarnesLogo.png" width="90" height="170" alt="Logo" />
				<h1><a href="<?= $linkTo('homePage'); ?>">Bjarnes Bank</a></h1>
			</div>
			<div id="menu">
				<ul>
                    <li><a href="<?= $linkTo('homePage'); ?>">Homepage</a></li>
                    <li class="current_page_item"><a href="#">View Transactions</a></li>
                    <li><a href="<?= $linkTo('bankAccount'); ?>">Create Account</a></li>
                    <li><a href="<?= $linkTo('logOut'); ?>">Log out</a></li>
				</ul>
			</div>
		</div>
	</div>

	<!------header wrapper ends ----------------->

    <div class="entry">

        <table><tr><th>Account Type</th>
                <th>Account Name</th>
                <th>Account Balance</th>
            </tr>

            <?php

            for($i = 0; $i < count($tranz); $i++){
                ?>
                test
                <?php

            }


            ?>
        </table>

    </div>
	<!------Login ends ----------------->
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>