<?php include "header.phtml" ?>


<div id="wrapper">
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<img src="/images/BjarnesLogo.png" width="90" height="170" alt="Logo" />
				<h1><a href="#">Bjarnes Bank</a></h1>
			</div>
			<div id="menu">
				<ul>
					<li ><a href=<?= $linkTo('loginPage'); ?>>Log in</a></li>
					<li class="current_page_item"><a href="#">Join</a></li>
				</ul>
			</div>
		</div>
	</div>

	<!------header wrapper ends ----------------->



	<div id="usercreate">
		<form method="POST" action="<?= $linkTo('accountCreate'); ?>">
			
		<div id="personinfo">
			<p> First Name  <input type="text" name="firstname" pattern="[A-Za-z]{2,}" title="Alphabetic characters only with no spaces." size="25"> </p>
			<p> Last Name  <input type="text" name="lastname" pattern="[A-Za-z]{2,}" title="Alphabetic characters only with no spaces." size="25"> </p>
			<p> Email  <input type="text" name="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email address" size="25"> </p>
			<p> Phone Number  <input type="text" name="phonenumber" size="25"> </p>
			<br>
			<p> Username  <input type="text" name="username" pattern="^[a-zA-Z0-9_\s]+$" title="Alphabetic characters only with no spaces." size="25"> </p>
			<p> Password  <input type="password" name="password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" size ="25"> </p>
			<p> Address  <input type="text" name="address" size ="25"> </p>
			<br>
		</div>
			<p> <input class="login" type="submit" value="Create"> </p>
		</form>
		<a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
	</div>
	<!------User Create ends ----------------->

</div>


<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>